---
abstract: 'State::Machine Implementation à la Moose'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires:
  perl: v5.14.2
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Machine-State
requires:
  Bubblegum: 0.31
  Exporter::Tiny: 0.038
  Function::Parameters: 1.0401
  Moose: 2.1211
  Throwable: 0.200011
  perl: v5.14.2
resources:
  bugtracker: https://github.com/alnewkirk/Machine-State/issues
  homepage: http://metacpan.org/release/Machine-State/
  repository: git://github.com/alnewkirk/Machine-State.git
version: 0.05
x_authority: cpan:AWNCORP
x_contributors:
  - 'Сергей Романов <sromanov-dev@yandex.ru>'
